# Generated by Django 3.2.4 on 2021-06-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerBody',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
