# Generated by Django 3.2.4 on 2021-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210608_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='intro',
            field=models.CharField(default='abc', max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='videoURL',
            field=models.CharField(default='abbbc', max_length=100),
        ),
    ]
